In [2]:
import torch

x = torch.ones(5)  # input tensor
y = torch.zeros(3, requires_grad=True)  # expected output
w = torch.randn(5, 3, requires_grad=True)
b = torch.randn(3, requires_grad=True)
z = torch.matmul(x, w)+b
loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)

In [9]:
print(f"Gradient function for z = {z.grad_fn}")
print(f"Gradient function for loss = {loss.grad_fn}")

Gradient function for z = <AddBackward0 object at 0x0000029AAFC98E20>
Gradient function for loss = <BinaryCrossEntropyWithLogitsBackward0 object at 0x0000029AAFB99E80>


In [2]:
loss.backward()
print(w.grad)
print(b.grad)


tensor([[0.0281, 0.0117, 0.0144],
        [0.0281, 0.0117, 0.0144],
        [0.0281, 0.0117, 0.0144],
        [0.0281, 0.0117, 0.0144],
        [0.0281, 0.0117, 0.0144]])
tensor([0.0281, 0.0117, 0.0144])


In [3]:
print(y.grad)

tensor([0.7955, 1.1048, 1.0322])


In [4]:
c = torch.tensor([1,2,3,4],requires_grad=True, dtype=torch.float32)
f = torch.tensor([[4,5,7,1], [1,3,2,1]],requires_grad=True, dtype=torch.float32)
f = f.T
k = torch.matmul(c, f)

s = torch.tensor([1,1], dtype=torch.float32)
s = s.T

res = torch.matmul(k, s)
res.backward()

print(f.grad)
print(c.grad)

C:\Users\hp\AppData\Local\Temp\ipykernel_13540\3924795215.py:7: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matricesor `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at  C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\TensorShape.cpp:2318.)
  s = s.T


None
tensor([5., 8., 9., 2.])


D:\Anaconda\envs\pt2_env\lib\site-packages\torch\_tensor.py:1104: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at  C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\build\aten\src\ATen/core/TensorBody.h:475.)
  return self._grad


In [6]:
inp = torch.eye(5, requires_grad=True)
out = (inp+1).pow(2)
out.backward(torch.ones_like(inp))
print(f"First call\n{inp.grad}")

# out.backward(torch.ones_like(inp), retain_graph=True)
# print(f"\nSecond call\n{inp.grad}")
# inp.grad.zero_()
# out.backward(torch.ones_like(inp), retain_graph=True)
# print(f"\nCall after zeroing gradients\n{inp.grad}")

First call
tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.],
        [2., 2., 2., 2., 4.]])
