In [ ]:
# License: BSD
# Author: Sasank Chilamkurthy

from __future__ import print_function, division

import torch
import torch.nn as nn
import torch.optim as optim
from torch.optim import lr_scheduler
import numpy as np
import torchvision
from torchvision import datasets, models, transforms
import matplotlib.pyplot as plt
import time
import os
import copy
from PIL import Image
plt.ion()   # interactive mode

In [ ]:
transform = transforms.Compose([
        transforms.Resize(224),
        # transforms.CenterCrop(224),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
    ])

In [ ]:
img=Image.open('E:/datasets/tire_dataset/leb/leb_1.jpg')
tensorImg = transform(img)
batch = tensorImg
batch = batch.reshape([1, batch.shape[0], batch.shape[1], batch.shape[2]]) 
print(batch.shape)

In [10]:
from my_model_class import myAlexNet, myMobileNetV2, myHelper

In [11]:
model_ft = myAlexNet()
model_ft.load_state_dict(torch.load('C:\\Users\\hp\\Desktop\\model_alexnet_static.pth'))
model_ft.eval()
output = model_ft(batch)
print(output)

tensor([[-0.8933, -8.9161,  5.6050,  1.7783,  2.3223]],
       grad_fn=<AddmmBackward0>)


In [13]:
traced = torch.jit.trace(model_ft, torch.rand(1, 3, 224, 224) )
traced.save('C:\\Users\\hp\\Desktop\\wrapped_alexnet.pt')
loaded = torch.jit.load('C:\\Users\\hp\\Desktop\\wrapped_alexnet.pt')
print(loaded(batch))

tensor([[-0.8933, -8.9161,  5.6050,  1.7783,  2.3223]],
       grad_fn=<AddmmBackward0>)


In [14]:
model2 = myMobileNetV2()
model2.load_state_dict(torch.load('C:\\Users\\hp\\Desktop\\model_mobilenet_v2_static.pth'))
model2.eval()
output = model2(batch)
print(output)

tensor([[-3.5950, -4.9406,  6.2244,  2.1279, -1.4213]],
       grad_fn=<AddmmBackward0>)


In [15]:
traced = torch.jit.trace(model2, torch.rand(1, 3, 224, 224) )
traced.save('C:\\Users\\hp\\Desktop\\wrapped_mobilenet_v2.pt')
loaded = torch.jit.load('C:\\Users\\hp\\Desktop\\wrapped_mobilenet_v2.pt')
print(loaded(batch))

tensor([[-3.5950, -4.9406,  6.2244,  2.1279, -1.4213]],
       grad_fn=<AddmmBackward0>)


In [9]:
model_rn = myHelper.get_ResNet50_vd()
model_rn.load_state_dict(torch.load('C:\\Users\\hp\\Desktop\\model_res50vd_static.pth'))
model_rn.eval()
output = model_rn(batch)
print(output)

tensor([[-1.7577, -3.2009,  5.5035, -0.0074, -0.9008]],
       grad_fn=<AddmmBackward0>)


保存成torchScript格式，.pt,可以在C++中加载

In [ ]:
traced = torch.jit.trace(model_rn, torch.rand(1, 3, 224, 224) )

In [ ]:
traced.save('C:\\Users\\hp\\Desktop\\wrapped_resnet50_vd.pt')
loaded = torch.jit.load('C:\\Users\\hp\\Desktop\\wrapped_resnet50_vd.pt')

In [8]:
print(loaded(batch))

tensor([[-1.7577, -3.2009,  5.5035, -0.0074, -0.9008]],
       grad_fn=<AddmmBackward0>)
